package com.radius.helpers;

/**
 * Created by kdl on 18.02.16.
 */
public enum ScreenTitles {
    CHATS_SCREEN, DIALOG_SCREEN, GROUP_SCREEN, VENUE_SCREEN, CREATE_CHAT_SCREEN,
    CONTACTS_SCREEN, CONTACT_PROFILE_SCREEN,
    SETTINGS_SCREEN, EDIT_PROFILE_SCREEN, LOGIN_SCREEN
}
